### ISSUE TITLE
这个我使用了没有成功

### ISSUE THREAD

**Issue by peixiaoqing** [wilsonchai8/idc_ping_monitor#1]
楼主你好，我使用了你项目里的python脚本，但是发现prometheus没有被推送过去数据，请问是我哪设置有问题吗，我的python版本是2.6 linux系统为7.2 。

**Comment by wilsonchai8** [comment]
查看下脚本的日志，如果是2xx，那证明数据采集是没有问题的。这时你要检查一下你的prometheus的配置，你的push-gateway是否正常工作？

**Comment by teesa-git** [comment]
楼主你好，发现如下问题。请给看下哪里的问题。
![QQ截图20190621163252](https://user-images.githubusercontent.com/52067473/59909429-40f41080-9442-11e9-9c59-6f2ae9ff652f.png)

Traceback (most recent call last):
  File "collection_to_prometheus.py", line 87, in <module>
    rrd_data_dir = os.path.join(data_dir , ISP)
NameError: name 'data_dir' is not defined

**Comment by Jason19910310** [comment]
我遇到了和楼上同样的问题, 请问怎么解决呢?

**Comment by teesa-git** [comment]
@Jason19910310 楼主还未答复。

**Comment by Jason19910310** [comment]
> @Jason19910310 楼主还未答复。

使用绝对目录就不会报错了

**Comment by Jason19910310** [comment]
@teesa-git 使用绝对目录

**Comment by wilsonchai8** [comment]
@teesa-git 如果是直接下载脚本然后执行，不应该会出现data_dir找不到的情况。你是怎么执行的？

**Comment by teesa-git** [comment]
> @teesa-git 如果是直接下载脚本然后执行，不应该会出现data_dir找不到的情况。你是怎么执行的？
@wilsonchai8 
已经找到问题的原因了，是data_dir 是在字典中定义，在全局中引用的问题。
另外，我还有一个问题，就是Table列的定义，出来好多列，就想要其中的个别列。这个在哪里设置？

**Comment by wilsonchai8** [comment]
你说的是在grafana里面的列吗？

**Comment by teesa-git** [comment]
> 你说的是在grafana里面的列吗？
@wilsonchai8 是的，另外你知道怎么在grafana 里面做路由图么？ 
![20190705135800](https://user-images.githubusercontent.com/52067473/60701068-ede38880-9f2c-11e9-81eb-a30cdf0dab14.png)

**Comment by wilsonchai8** [comment]
你自己去看grafana的文档吧
