### ISSUE TITLE
采集的数据都是ttl 0，丢包率100%

### ISSUE THREAD

**Issue by jorney88** [wilsonchai8/idc_ping_monitor#2]
按照你的步骤，服务启动也正常，但是采集到的数据都是0，丢包率100%
![image](https://user-images.githubusercontent.com/7877579/62294285-2aa78e80-b49d-11e9-8665-5acaf437259b.png)

**Comment by wilsonchai8** [comment]
1、有可能是那几个ip已经无法使用，你可以去smokeping/location/telcom中找出ip出来，看是否能够ping通
2、或者使用新版本，自动获取可用ip

**Comment by jorney88** [comment]
> 1、有可能是那几个ip已经无法使用，你可以去smokeping/location/telcom中找出ip出来，看是否能够ping通
> 2、或者使用新版本，自动获取可用ip

所有的IP都不行，我直接ping 测试了一下是可以的。请问他是在怎么fping 这些IP的

**Comment by cynosuretw** [comment]
如果你的 smokeping config 內, step 設定為預設的300秒,  那執行collection_to_prometheus.py 會失敗.

**Comment by wilsonchai8** [comment]
@jorney88 fping也是使用icmp协议去做存活性探测的。能不能检查一下，你的smokeping是否正常启动，有没有报错

**Comment by jorney88** [comment]
> @jorney88 fping也是使用icmp协议去做存活性探测的。能不能检查一下，你的smokeping是否正常启动，有没有报错

Aug  2 20:50:55 centos-autompushgateway-4059 smokeping[7354]: Restarting due to HUP signal.
Aug  2 20:50:55 centos-autompushgateway-4059 smokeping[7354]: Reloading configuration.
Aug  2 20:50:55 centos-autompushgateway-4059 smokeping[7354]: Not entering multiprocess mode for just a single probe.
Aug  2 20:50:55 centos-autompushgateway-4059 smokeping[7354]: FPing: probing 97 targets with step 60 s and offset 42 s.
Aug  2 20:51:05 centos- smokeping[7354]: got INT signal, terminating.
Aug  2 20:51:08 centos- smokeping[7551]: Starting syslog logging
Aug  2 20:51:08 centos- smokeping[7555]: Smokeping version 2.007003 successfully launched.
Aug  2 20:51:08 centos- smokeping[7555]: Not entering multiprocess mode for just a single probe.
Aug  2 20:51:08 centos- smokeping[7555]: FPing: probing 97 targets with step 60 s and offset 50 s

没用报错

**Comment by wilsonchai8** [comment]
打开smokeping的debug模式，看下日志：

/usr/local/smokeping/bin/smokeping --debug
