### ISSUE TITLE
如果你的 smokeping config 內, step 設定為預設的300秒,  那執行collection_to_prometheus.py 會失敗.

### ISSUE THREAD

**Issue by wilsonchai8** [wilsonchai8/idc_ping_monitor#3]
如果你的 smokeping config 內, step 設定為預設的300秒,  那執行collection_to_prometheus.py 會失敗.

_Originally posted by @cynosuretw in https://github.com/wilsonchai8/idc_ping_monitor/issues/2#issuecomment-517542603_

**Comment by wilsonchai8** [comment]
能否给出具体的报错信息？

**Comment by cynosuretw** [comment]
> 能否给出具体的报错信息？

Traceback (most recent call last):
  File "collection_to_prometheus.py", line 71, in <module>
    (lost_package_num , rrt) = getMonitorData(os.path.join(paras['data_dir'] , ISP , filename))
  File "collection_to_prometheus.py", line 59, in getMonitorData
    lost_package_num = int(results[2][0][1])
TypeError: int() argument must be a string or a number, not 'NoneType'   

60 應該就是 smokeping 的 step 時間.

**Comment by wilsonchai8** [comment]
看起来应该是step导致的，由于采集间隔变化了，60的粒度导致采集不到数据，所以报错了

**Comment by wilsonchai8** [comment]
目前如果要修改配置文件中的step的话，那就要在脚本同步修改step了：
last_update = rrd_info['last_update'] - 60
