### ISSUE TITLE
你好，我想问下，为啥我的grafana上面省份显示的是拼音

### ISSUE THREAD

**Issue by skyisfuck** [wilsonchai8/idc_ping_monitor#4]
![image](https://user-images.githubusercontent.com/35327374/63217017-471c1a00-c171-11e9-81e1-e2df3877ed6a.png)

**Comment by wilsonchai8** [comment]
能否打开prometheus ，看下原始的日志是啥样子的？

**Comment by wilsonchai8** [comment]
已经修复，请更新代码

**Comment by skyisfuck** [comment]
更新代码后，报错
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 66-67: Body ('甘肃') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encode
d in UTF-8.

然后我把metrics这一行代码中加上了encode(‘utf-8’)后
 metrics = 'smokeping_%s{instance=\"%s\" , ISP=\"%s\" , IDC=\"%s\" , alias=\"%s\"} %d' % (key , instance , ISP , 'SH' , paras['province_map'].get(instance).**encode('ut
f-8')** , value)

/tmp/idc_ping_monitor.log中request请求400 return code
2019-08-20 23:04:02,328 - http://192.168.100.104:9091/metrics/job/smokeping-collected-TENCENT/instance/beijing - smokeping_lost_package_num{instance="beijing" , ISP="TENCENT" , IDC="SH" , alias="b'\xe5\x8c\x97\xe4\xba\xac'"} 0 - 400

**Comment by skyisfuck** [comment]
你好，我这边最后在request_code中加入encode('utf-8')，正常post到prometheus
request_code = requests.post(pushgateway , data='{0}\n'.format(metrics)**.encode('utf-8'),** headers=headers)
![图片](https://user-images.githubusercontent.com/35327374/63396149-ae97cb00-c3f8-11e9-98c8-69af44181fbc.png)

**Comment by wilsonchai8** [comment]
好的，非常感谢
